### ISSUE TITLE
Game Hunter not connecting.

### ISSUE THREAD

**Issue by davidvondle** [astrospark/bolorama#1]
![070AD305-4E0D-45F6-A41F-374F069E3241](https://user-images.githubusercontent.com/915950/207531606-f0564a31-cd3d-4e00-9e93-a2f4e91f3cd8.jpeg)

I don’t know if this goes here and feel free to take this down if it doesn’t, but I saw your video about the Bolo tracker, installed everything and tried to get a game going but I got the error “connection to Bolo.Astrospark.com timed out”.  I am connected to the web, and I’m forwarding ports 40000-50000 to the machine.  Any idea what’s going on? Thanks!

**Comment by squires** [comment]
It might be an issue with an update I recently deployed. Not positive because I realize I made a mistake in my testing before I shut down the running instance. As a precaution I have reverted to the previous release while I do more testing. Sorry for the inconvenience.

**Comment by squires** [comment]
In case the last message was confusing, it should be working now. I'm running a previous version.

The new version added notifications, so those won't be available. But they were just a convenience.

**Comment by davidvondle** [comment]
Working now for me thank you!!!
